# Generated by Django 5.1.7 on 2025-03-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Código postal')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('paternal_surname', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('maternal_surname', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Número de teléfono')),
                ('street', models.CharField(max_length=100, verbose_name='Calle')),
                ('interior_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número interior')),
                ('external_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Exteranl interior')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Código postal')),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.colony')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postal_code', models.PositiveBigIntegerField(verbose_name='Código postal')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.municipality')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.state'),
        ),
    ]
