# Generated by Django 5.1.7 on 2025-03-22 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='colony',
            name='postal_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.postalcode'),
        ),
    ]
