# Generated by Django 5.1.7 on 2025-03-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_client_postal_code_alter_colony_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='external_number',
            field=models.CharField(blank=True, null=True, verbose_name='Exteranl interior'),
        ),
        migrations.AlterField(
            model_name='client',
            name='interior_number',
            field=models.CharField(blank=True, null=True, verbose_name='Número interior'),
        ),
    ]
