# Generated by Django 5.1.7 on 2025-03-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_number', models.PositiveIntegerField(verbose_name='Número de servicio')),
                ('meter_number', models.CharField(max_length=11, verbose_name='Número de medidor')),
                ('rmu', models.CharField(max_length=100, verbose_name='RMU')),
                ('threads', models.PositiveIntegerField(verbose_name='Hilos')),
                ('account', models.CharField(max_length=100, verbose_name='Cuenta')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.rate')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_kWh_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo de kW anterior')),
                ('current_kWh_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo de kWh actual')),
                ('start_period', models.DateField(verbose_name='Fecha de inicio del periodo facturado')),
                ('end_period', models.DateField(verbose_name='Fecha de fin del periodo facturado')),
                ('total_kWh_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo total de kWh')),
                ('payment_deadline', models.DateField(verbose_name='Límite de pago')),
                ('cut_off_date', models.DateField(verbose_name='Fecha de corte')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
